
export const Game = {
    pixelScale: 1,
    paused: false,
    stepOneFrame: false,
    showhitboxes: false,
    debugtext: "",
    dtDisplay: 0,
    fpsDisplay: 0,
    dt: 0,
    fps: 0,
    time: 0,
    lastTimestamp: 0,
    keys: {},
    inputs: {},
    spritesheets: {},
    sounds: {},
    createdGameObjects: 0,
    objects: [],
    platforms: [],
    player: null,
    mousePos: { x: 0, y: 0 },
    scrollX: 0,
    scrollY: 0,
    currentScrollX: 0,
    currentScrollY: 0,
    maxScrollY: 0,
    platformHorizontalSpacing: 87.5,
    platformVerticalSpacing: 37.5,
    lastPlatformX: 0,
    nextPlatformY: 250,
    lastPlatformType: 0,
    canvas: {},
    zoom: 3,
    actx: new (window.AudioContext || window.webkitAudioContext)({latencyHint:'interactive'}),
    tick: undefined,
    draw: undefined,
    setBgColor: function (color) {
        window.document.body.style.backgroundColor = color;
    },
};
